version: '3.8'
services:
  influxdb:
    image: influxdb:2.0
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
      - ./scripts:/docker-entrypoint-initdb.d
    environment:
      INFLUXDB_INIT_MODE: ${INFLUXDB_INIT_MODE}
      INFLUXDB_INIT_USERNAME: ${INFLUXDB_INIT_USERNAME}
      INFLUXDB_INIT_PASSWORD: ${INFLUXDB_INIT_PASSWORD}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_BUCKET_RAW: ${INFLUXDB_BUCKET_RAW}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}

  python_app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: python_app
    depends_on:
      - influxdb
    environment:
      INFLUXDB_URL: ${INFLUXDB_URL}
      INFLUXDB_TOKEN: ${INFLUXDB_TOKEN}
      INFLUXDB_ORG: ${INFLUXDB_ORG}
      INFLUXDB_BUCKET: ${INFLUXDB_BUCKET}
      INFLUXDB_BUCKET_RAW: ${INFLUXDB_BUCKET_RAW}
      AWS_INFLUXDB_URL: ${AWS_INFLUXDB_URL}
      AWS_INFLUXDB_TOKEN: ${AWS_INFLUXDB_TOKEN}
      DRY_RUN_MODE: ${DRY_RUN_MODE}
      DATA_COLLECTION_INTERVAL_SECONDS: ${DATA_COLLECTION_INTERVAL_SECONDS}
      DATA_UPLOAD_INTERVAL_SECONDS: ${DATA_UPLOAD_INTERVAL_SECONDS}
    volumes:
      - ./app:/app

volumes:
  influxdb-data:
