version: '3.8'
services:
  influxdb:
    build: influxdb
    container_name: influxdb
    ports:
      - "8086:8086"
    volumes:
      - influxdb-data:/var/lib/influxdb2
    environment:
      DOCKER_INFLUXDB_URL: ${DOCKER_INFLUXDB_URL}
      DOCKER_INFLUXDB_INIT_MODE: ${DOCKER_INFLUXDB_INIT_MODE}
      DOCKER_INFLUXDB_INIT_USERNAME: ${DOCKER_INFLUXDB_INIT_USERNAME}
      DOCKER_INFLUXDB_INIT_PASSWORD: ${DOCKER_INFLUXDB_INIT_PASSWORD}
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_BUCKET_RAW: ${DOCKER_INFLUXDB_INIT_BUCKET_RAW}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      DOCKER_INFLUXDB_HTTP_AUTH_ENABLE: ${DOCKER_INFLUXDB_HTTP_AUTH_ENABLE}

  python_app:
    build:
      context: app
      dockerfile: Dockerfile
    container_name: python_app
    depends_on:
      - influxdb
    privileged: true
    devices:
      - /dev/gpiomem:/dev/gpiomem
    environment:
      DOCKER_INFLUXDB_URL: ${DOCKER_INFLUXDB_URL}
      DOCKER_INFLUXDB_INIT_ADMIN_TOKEN: ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
      DOCKER_INFLUXDB_INIT_ORG: ${DOCKER_INFLUXDB_INIT_ORG}
      DOCKER_INFLUXDB_INIT_BUCKET: ${DOCKER_INFLUXDB_INIT_BUCKET}
      DOCKER_INFLUXDB_INIT_BUCKET_RAW: ${DOCKER_INFLUXDB_INIT_BUCKET_RAW}
      AWS_INFLUXDB_URL: ${AWS_INFLUXDB_URL}
      AWS_INFLUXDB_TOKEN: ${AWS_INFLUXDB_TOKEN}
      DRY_RUN_MODE: ${DRY_RUN_MODE}
      DHT11_CONNECTED: ${DHT11_CONNECTED}
      SEN0193_CONNECTED: ${SEN0193_CONNECTED}
      DATA_COLLECTION_INTERVAL_SECONDS: ${DATA_COLLECTION_INTERVAL_SECONDS}
      DATA_UPLOAD_INTERVAL_SECONDS: ${DATA_UPLOAD_INTERVAL_SECONDS}
    volumes:
      - ./app:/app
      - /sys/class/gpio:/sys/class/gpio

volumes:
  influxdb-data:
